<?php

declare(strict_types=1);

namespace Synloquent\Laravel\Export;

use Synloquent\Laravel\Protocol\CanonicalJson;

final class TypeScriptGenerator
{
    public function __construct(private ManifestBuilder $manifest) {}

    public function generate(): string
    {
        $manifest = $this->manifest->build();
        $content = "// Generated by Synloquent. Edit Laravel exports and regenerate.\nimport type { BindSchema, BindCommands, BindScopes } from '@synloquent/client'\n\nexport const backendSchema = ".CanonicalJson::encode($manifest)." as const\n\nexport type BackendModels = BindSchema<typeof backendSchema>\nexport type BackendCommands = BindCommands<typeof backendSchema>\nexport type BackendScopes = BindScopes<typeof backendSchema>\n";

        return $content;
    }
}
