<?php

return [
    'exports' => [],
    'additional_capabilities' => [],
    'commands' => [],
    'scopes' => [],
    'effects' => [],
    'capture_contract' => null,
    'actor_resolver' => null,
    'connection' => null,
    'schema_version' => 1,
    'dataset_generation' => '1',
    'cursor_secret' => env('SYNLOQUENT_CURSOR_SECRET', env('APP_KEY')),
    'route_prefix' => 'synloquent/v1',
    'middleware' => ['api', 'auth'],
    'max_query_nodes' => 100,
    'max_query_depth' => 8,
    'max_batch_size' => 100,
    'max_page_size' => 1000,
    'max_snapshot_rows' => 200000,
    'max_snapshot_bytes' => 67108864,
    'profile_snapshots' => false,
    'max_pull_bytes' => 8388608,
    'max_pull_materialization_members' => 5000,
    'max_delta_transactions' => 1000,
    'max_delta_records' => 1000,
    'max_delta_bytes' => 8388608,
    'max_request_bytes' => 1048576,
];
